default: &default
  endpoint: 'https://acme-v01.api.letsencrypt.org/'
  email: 'ben.schaaf@gmail.com'
  domain: 'demo.citadel.tv'

  # in Rails.root, path to private key
  private_key: 'key/keyfile.pem'

  # in Rails.root, path where certificates
  output_cert_dir: 'certificates'

  # in Rails.root, path where challenge token
  # will be stored in case when DB will not be used
  challenge_dir_name: 'challenge'

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
