default: &default
  # topic or none
  type: tpoic
  # id of the topic to take news from. Optional if type is none
  id: 2
  # Number of recent threads to display. Optional if type is none
  display: 3

development:
  <<: *default
  database: citadel_dev

test:
  <<: *default
  database: citadel_test

production:
  <<: *default
  database: citadel_prod
